name: Messenger Bot Deploy

on:
  push:
    branches:
      - main   # শুধু main ব্রাঞ্চে push হলে deploy হবে

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --production

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ubuntu
          server-ip: ${{ secrets.SERVER_IP }}
          remote-path: /var/www/messenger-bot
          local-path: .


