name: MeCyber Bot

on:
  push:
    branches:
      - main   # main ব্রাঞ্চে push করলে রান হবে

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install node-fetch@2

    - name: Run bot
      run: node sendMessage.js
      env:
        PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
        GROUP_THREAD_ID: ${{ secrets.GROUP_THREAD_ID }}
